language: node_js
node_js:
  - 8
  - 6
  - 4

# blocklist version commits
branches:
  except:
    - /^v[0-9]/

jobs:
  include:
    - stage: release
      node_js: 7
      branches:
        only: master
      script:
        - git config --global user.email "nordnet-release@localhost"
        - git config --global user.name "nordnet-release"
        - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release
