language: node_js
node_js:
  - 7
  - 6
  - 4

jobs:
  include:
    - stage: release
      node_js: 7
      script:
        - 'git config --global user.email "nordnet-release@localhost"'
        - 'git config --global user.name "nordnet-release"'
        - 'npm run semantic-release'
