language: node_js
node_js:
  - 8
  - 6
  - 4

# blocklist version commits
branches:
  except:
    - /^v[0-9]/

jobs:
  include:
    - stage: release
      script:
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "no releases for pull-requests; fi"
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then exit 0; fi;
        - git config --global user.email "nordnet-release@localhost"
        - git config --global user.name "nordnet-release"
        - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release
