language: node_js
node_js:
  - 8
  - 6
  - 4

# blocklist version commits
branches:
  except:
    - /^v[0-9]/

jobs:
  include:
    - stage: release
      install: echo "hello"
      script:
        - git config --global user.email "nordnet-release@localhost"
        - git config --global user.name "nordnet-release"
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then npm install; fi
        - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release; fi
